version: "3.10"

name: "io-docker"

services:
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Docker/Dockerfile
    ports:
      - "80:80"

  backend:
    container_name: io-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
